[package]
name = "rs_voice_controller"
version = "0.1.0"
edition = "2021"  

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
dotenv = "0.15.0"
poise = "0.6.1"
sqlx = { version = "0.7.3", features = ["runtime-tokio-native-tls", "sqlite"]}
tokio = { version = "1.35.1", features = ["rt-multi-thread"] }
